name: patbert
channels:
  - plotly
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=8.0.0=py310h38b8b19_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py310haa95532_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h2bbff1b_12
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.0=h2bbff1b_0
  - ca-certificates=2023.05.30=haa95532_0
  - cairo=1.16.0=h1c23506_3
  - certifi=2023.5.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cpuonly=2.0=0
  - cryptography=38.0.4=py310h21b164f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310haa95532_0
  - et_xmlfile=1.1.0=py310haa95532_0
  - exceptiongroup=1.0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6c2663c_0
  - fastparquet=0.5.0=py310h9128911_2
  - fftw=3.3.9=h2bbff1b_1
  - filelock=3.9.0=py310haa95532_0
  - flit-core=3.8.0=py310haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hc0defaf_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - fribidi=1.0.10=h62dcd97_0
  - getopt-win32=0.1=h2bbff1b_0
  - gflags=2.2.2=ha925a31_0
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.5.0=hd77b12b_0
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=2.50.0=h7eca76f_1
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - gts=0.7.6=h63ab5a1_3
  - h5py=3.7.0=py310hfc34f40_0
  - harfbuzz=4.3.0=hb646838_1
  - hdf5=1.10.6=h1756f20_1
  - huggingface_hub=0.10.1=py310haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipython=8.8.0=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - joblib=1.1.1=py310haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.17.3=py310haa95532_0
  - jupyter_client=7.4.9=py310haa95532_0
  - jupyter_core=5.1.1=py310haa95532_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libboost=1.73.0=h6c2663c_12
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=12.0.0=default_h627e005_2
  - libcurl=8.1.1=h86230a5_1
  - libdeflate=1.8=h2bbff1b_5
  - libevent=2.1.12=hcc03200_0
  - libffi=3.4.2=hd77b12b_6
  - libgd=2.3.3=hd77b12b_2
  - libiconv=1.16=h2bbff1b_2
  - libllvm14=14.0.6=h4157e71_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_2
  - libthrift=0.15.0=he49ee6e_2
  - libtiff=4.5.0=h6c2663c_1
  - libuv=1.40.0=he774522_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - llvmlite=0.40.0=py310hf2fb9eb_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.6.2=py310haa95532_0
  - matplotlib-base=3.6.2=py310h1094b8e_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - networkx=2.8.4=py310haa95532_1
  - numba=0.57.0=py310h4ed8f06_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy-base=1.21.5=py310h206c741_3
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.10=py310h2bbff1b_0
  - openssl=1.1.1u=h2bbff1b_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.2=py310h4ed8f06_0
  - pango=1.50.7=h78c2152_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py310hd77b12b_2
  - pip=22.3.1=py310haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=2.5.2=py310haa95532_0
  - plotly=5.13.1=py_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - polars=0.16.9=py310h87d50f1_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poppler=22.12.0=h268424c_0
  - poppler-data=0.4.11=haa95532_1
  - prompt-toolkit=3.0.36=py310haa95532_0
  - protobuf=3.20.3=py310hd77b12b_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pyarrow=8.0.0=py310h26aae1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pygraphviz=1.9=py310h2bbff1b_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - pytest=7.1.2=py310haa95532_0
  - python=3.10.9=h966fe2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.0=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2022.7=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pyyaml=6.0=py310h2bbff1b_1
  - qt=5.15.7=haa95532_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h3ad3cdb_4
  - re2=2022.04.01=hd77b12b_0
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.28.1=py310haa95532_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-learn=1.2.0=py310hd77b12b_0
  - scipy=1.10.0=py310hb9afe5d_0
  - setuptools=65.6.3=py310haa95532_0
  - shellingham=1.5.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=8.2.2=py310haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - thrift=0.17.0=py310hd77b12b_0
  - tk=8.6.12=h2bbff1b_0
  - tokenizers=0.11.4=py310he5181cf_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - torchaudio=0.13.0=py310_cpu
  - torchvision=0.13.1=cpu_py310h378ed51_0
  - tornado=6.2=py310h2bbff1b_0
  - tqdm=4.64.1=py310haa95532_0
  - traitlets=5.7.1=py310haa95532_0
  - transformers=4.24.0=py310haa95532_0
  - typer=0.4.1=py310haa95532_0
  - typing-extensions=4.4.0=py310haa95532_0
  - typing_extensions=4.4.0=py310haa95532_0
  - tzdata=2022g=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - urllib3=1.26.14=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - autopep8==2.0.1
      - boto3==1.28.45
      - botocore==1.31.45
      - colorlog==6.7.0
      - dirty-cat==0.3.0
      - enum34==1.1.10
      - fastcore==1.5.27
      - htmlmin==0.1.12
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.1
      - ipython-genutils==0.2.0
      - jmespath==1.0.1
      - json5==0.9.11
      - kaleido==0.1.0.post1
      - lovely-numpy==0.2.8
      - lovely-tensors==0.1.14
      - mistune==2.0.5
      - numpy==1.24.4
      - omegaconf==2.3.0
      - pycodestyle==2.10.0
      - pydantic==1.10.7
      - pytorch-pretrained-bert==0.6.2
      - pyzmq==25.0.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - s3transfer==0.6.2
      - send2trash==1.8.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - tangled-up-in-unicode==0.2.0
      - tinycss2==1.2.1
      - typeguard==2.13.3
      - uri-template==1.2.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.6
      - y-py==0.5.9
prefix: C:\Users\fjn197\Miniconda3\envs\patbert
