env: local
output_dir: ../outputs/features
tokenized_dir_name: "tokenized"
paths:
  run_name: "_test"
  save_features_dir_name: "features" # saves in this directory on azure. If not provided use run_name.
loader:
  # can provide formatted data or features
  data_dir:  ../data/formatted/synthea500 # ../outputs/features_test # ../data/formatted/synthea500_icd10 #../outputs/data_icd10
  concepts: [
    diagnose
  ]
  batch_size: 64
  chunksize: 300

features:
  age: 
    round: 2
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']

tokenizer:
  sep_tokens: true
  cls_token: true
  truncation: null
  #cutoffs:
   # D: 3 # diagnosis
   # M: 4 # medication

excluder:
  min_len: 2

split_ratios:
  pretrain: 0.72 # 80% of 90%
  finetune: 0.18 # 20% of 90%
  test: 0.1
handler:
  min_age: -1
  max_age: 120

# can be a list
# exclude_pids: outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/test_pids.pt
# assigned_pids: 
  # can be a list
  # pretrain: 
  #  - outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/fold_1/val_pids.pt
#predefined_splits_dir: ../outputs/data_icd10/tokenized #../outputs/features_test/tokenized

